version: '3'

volumes:
    log-data:
        driver: local
    prometheus-data:
    loki-data:
    grafana-storage:

services:
    demo-app:
        build:
            context: app
        ports:
            - '8080:8080'
        volumes:
            - log-data:/var
        depends_on:
            - fluent-bit
            - otel-collector

    fluent-bit:
        image: fluent/fluent-bit:latest
        volumes:
            - ./fluent-bit/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
            - log-data:/var
        ports:
            - '3000:3000'

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: [--config=/etc/otel-collector-config.yaml]
        volumes:
            - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '13133:13133'
        depends_on:
            - fluent-bit

    loki:
        image: grafana/loki:latest
        ports:
            - '3100:3100'
        volumes:
            - ./loki/loki.yaml:/etc/loki/local-config.yaml
            - loki-data:/loki
        depends_on:
            - otel-collector

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - '16686:16686'
            - '14268'
            - '14250'
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        depends_on:
            - otel-collector

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
            - prometheus-data:/prometheus
        command:
            - --web.enable-lifecycle
            - --config.file=/etc/prometheus.yaml
        restart: always
        ports:
            - '9090:9090'
        depends_on:
            - otel-collector

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        ports:
            - '8081:3000'
        depends_on:
            - prometheus
            - loki
            - jaeger
        volumes:
            - './grafana/grafana.ini:/etc/grafana/grafana.ini'
            - 'grafana-storage:/var/lib/grafana'
