version: '3'

volumes:
    log-data:
        driver: local
    prometheus-data:
    loki-data:
    grafana-storage:

services:
    demo-app:
        build:
            context: app
        ports:
            - '8080:8080'
        volumes:
            - log-data:/var
        depends_on:
            - otelcollector

    otelcollector:
        image: otel/opentelemetry-collector-contrib:latest
        command: [--config=/etc/otel-collector-config.yaml]
        volumes:
            - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '3030:3030'
            - '8889:8889' # Prometheus exporter metrics
            - '13133:13133' # health_check extension

    loki:
        image: grafana/loki:latest
        ports:
            - '3100:3100'
        volumes:
            - ./loki/loki.yaml:/etc/loki/local-config.yaml
            - loki-data:/etc/loki
        command:
            - -config.file=/etc/loki/local-config.yaml
            - -log.level=error
            - useradd -u 10001 loki
            - chown loki:loki /etc/loki/*
        depends_on:
            - otelcollector

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - '4317:4317'
            - '4318:4318'
            - '9411:9411'
            - '16686:16686' # Jaeger UI
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        depends_on:
            - otelcollector

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus.yaml
            - prometheus-data:/prometheus
        command:
            - --web.enable-lifecycle
            - --config.file=/etc/prometheus.yaml
            - --enable-feature=otlp-write-receiver
        restart: always
        ports:
            - '9090:9090'
        depends_on:
            - otelcollector

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        ports:
            - '8081:3000'
        depends_on:
            - prometheus
            - loki
            - jaeger
        volumes:
            - './grafana/grafana.ini:/etc/grafana/grafana.ini'
            - 'grafana-storage:/var/lib/grafana'
