receivers:
    otlp:
        protocols:
            grpc:
            http:
                endpoint: '0.0.0.0:3030'

exporters:
    otlp: # jaeger on otlp interface
        # disable tls
        endpoint: 'jaeger:4317'
        tls:
            insecure: true

    # logging: # Will print to stdout. Kindda noisy so turned off

    loki:
        endpoint: http://loki:3100/loki/api/v1/push

    prometheus:
        endpoint: '0.0.0.0:9090'

service:
    pipelines:
        logs:
            receivers: [otlp]
            exporters: [loki]
        traces:
            receivers: [otlp]
            exporters: [otlp] # jaeger on otlp
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
