receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:3030"

exporters:
  otlp:

  loki:

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
    traces:
      receivers: [otlp]
      exporters: [tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
