env:
    flush_interval: 1

service:
    flush: ${flush_interval}
    log_level: info

pipeline:
    inputs:
        - name: tail
          path: /var/log.log
          tag: demo-app
        - name: opentelemetry
    outputs:
        # - name: stdout
        #   match: '*'
        - name: opentelemetry
          match: '*'
          host: collector
          port: 3030
          metrics_uri: /v1/metrics
          logs_uri: /v1/logs
          traces_uri: /v1/traces
          log_response_payload: True
          tls: 'off'
          tls.verify: 'off'
          # add user-defined labels
          add_label: app fluent-bit
